### ISSUE TITLE
running test_t5.sh

### ISSUE THREAD

**Issue by jh-skaion** [EagleW/Stage-wise-Fine-tuning#3]
hello @EagleW,
i was trying to test your model but i am getting an error:
![image](https://user-images.githubusercontent.com/82824999/135347965-6a4be1ca-5230-4ff3-bc47-97759944048d.png)

is there anything else i need to do? where "finetune_t5_test.py" come from?

thank you for you time

**Comment by EagleW** [comment]
Hi can you try to replace the finetune_t5_test.py with finetune_t5.sh Thank you

**Comment by jh-skaion** [comment]
Thanks @EagleW
