### ISSUE TITLE
Plug-and-play function

### ISSUE THREAD

**Issue by wygao8** [EagleW/Stage-wise-Fine-tuning#5]
Hi @EagleW, I tried to generate sentences for triples in TACRED but failed.

I downloaded your model and generate formatted `test.source`, `test.target`, `test.target_eval`, `test.target2_eval`, `test.target3_eval` for triples in TACRED. Then I ran `test_t5.sh` and got an error as follows:
`TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'`

So I was wondering whether there is any plug-and-play function to generate sentences for triples other datasets by using your fine-tuned model.

Thanks in advance.

**Comment by EagleW** [comment]
Hi Thank you for your interest in our research! Would you please share your generated examples with us? Have you followed the code as webnlg_tree.py? Thanks!

**Comment by wygao8** [comment]
Thanks! 
I checked `webnlg_tree.py` out and found that I didn't use `json.dumps()` to write source files.
It works fine now!
